// Todas as tabelas que forem referentes a geracao automatica de personagem.

// Tabelas de geracao de atributos.
var tabelas_geracao = {
  // Peguei do livro do mestre.
  barbaro: { 
		atributos: ['forca', 'destreza', 'constituicao', 'sabedoria', 'inteligencia', 'carisma' ],
    por_nivel: {
       1: { moedas: { ouro: 200 }, 
            armadura: { nome: 'brunea', obra_prima: true }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       2: { moedas: { ouro: 1200 }, 
            armadura: { nome: 'peitoral_de_aco', obra_prima: true, }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       3: { moedas: { ouro: 1700 }, 
            armadura: { nome: 'peitoral_de_aco', obra_prima: true, }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       4: { moedas: { ouro: 2500 }, 
            armadura: { nome: 'peitoral_de_aco', obra_prima: true, }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       5: { moedas: { ouro: 2500 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 1 }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       6: { moedas: { ouro: 3800 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 1 }, 
            armas: [ { chave: 'machado_grande', bonus: 0, obra_prima: true },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       7: { moedas: { ouro: 3500 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 1 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       8: { moedas: { ouro: 3500 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 1 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
       9: { moedas: { ouro: 6000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 2 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 0, obra_prima: false }, ],
            aneis: [],
      },
      10: { moedas: { ouro: 1000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 2 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [],
      },
      11: { moedas: { ouro: 1000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [],
      },
      12: { moedas: { ouro: 1000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [],
      },
      13: { moedas: { ouro: 9000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 1, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [],
      },
      14: { moedas: { ouro: 11000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 2, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_2', em_uso: true } ],
      },
      15: { moedas: { ouro: 14000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 3, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 1, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_2', em_uso: true } ],
      },
      16: { moedas: { ouro: 25000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 3 }, 
            armas: [ { chave: 'machado_grande', bonus: 4, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 2, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_2', em_uso: true } ],
      },
      17: { moedas: { ouro: 3000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 4 }, 
            armas: [ { chave: 'machado_grande', bonus: 4, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 2, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_2', em_uso: true } ],
      },
      18: { moedas: { ouro: 17000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 5 }, 
            armas: [ { chave: 'machado_grande', bonus: 4, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 3, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_3', em_uso: true } ],
      },
      19: { moedas: { ouro: 16000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 5 }, 
            armas: [ { chave: 'machado_grande', bonus: 4, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 3, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_3', em_uso: true } ],
      },
      20: { moedas: { ouro: 66000 }, 
            armadura: { nome: 'peitoral_de_aco', bonus_magico: 5 }, 
            armas: [ { chave: 'machado_grande', bonus: 4, obra_prima: false },
                     { chave: 'arco_longo_composto', bonus: 3, obra_prima: false }, ],
            aneis: [ { chave: 'protecao_3', em_uso: true } ],
      },
    },
	},
  bardo: { 
		atributos: [ 'carisma', 'inteligencia', 'destreza', 'constituicao', 'forca', 'sabedoria' ],
	},
  clerigo: { 
		atributos: [ 'sabedoria', 'constituicao', 'forca', 'carisma', 'inteligencia',  'destreza' ],
	},
  druida: { 
		atributos: [ 'sabedoria', 'destreza', 'constituicao', 'inteligencia', 'forca', 'carisma' ],
	},
  guerreiro: { 
		atributos: [ 'forca', 'constituicao', 'destreza', 'sabedoria', 'inteligencia', 'carisma' ],
	},
  feiticeiro: { 
		atributos: [ 'carisma', 'destreza', 'constituicao', 'sabedoria', 'inteligencia', 'forca' ],
	},
  ladino: { 
		atributos: [ 'destreza', 'inteligencia', 'constituicao', 'forca', 'sabedoria', 'carisma' ],
	},
  mago: { 
		atributos: [ 'inteligencia', 'destreza', 'constituicao', 'sabedoria', 'forca', 'carisma' ],
	},
  monge: { 
		atributos: [ 'sabedoria', 'forca', 'destreza', 'constituicao', 'inteligencia', 'carisma' ],
	},
  paladino: { 
		atributos: [ 'carisma', 'forca', 'sabedoria', 'constituicao', 'inteligencia', 'destreza' ],
	},
  ranger: { 
		atributos: [ 'destreza', 'forca', 'constituicao', 'sabedoria', 'inteligencia', 'carisma' ],
	},
  // classes NPC: nao existe uma tabela para esses, coloquei o que achei mais adequado.
  adepto: { 
		atributos: [ 'sabedoria', 'destreza', 'constituicao', 'inteligencia', 'forca', 'carisma' ],
	},
  // Esse ta muito ruim...
  aristocrata: { 
		atributos: [ 'destreza', 'inteligencia', 'forca', 'carisma', 'constituicao', 'sabedoria' ],
	},
  plebeu: { 
		atributos: [ 'forca', 'constituicao', 'sabedoria', 'destreza', 'inteligencia', 'carisma' ],
	},
  // esse aqui varia de acordo com as escolhas da area de expertise.
  expert: { 
		atributos: [ 'inteligencia', 'forca', 'destreza', 'constituicao', 'sabedoria', 'carisma' ],
	},
  combatente: { 
		atributos: [  'forca', 'constituicao', 'destreza', 'sabedoria', 'inteligencia', 'carisma' ],
	},
};
